# Generated by Django 5.1.7 on 2025-09-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard_thumbnails/'),
        ),
    ]
